Missing plot fix
qiime2/q2-gneiss pull request #29
Opened 2018-01-11 07:35 UTC by mortonjt

This fixes #28 .  Updating the test cases to sanity check that the plots are actually generated.

2018-01-11 07:38 UTC, mortonjt commented
Looks like something weird is going on with conda

2018-01-11 07:42 UTC, mortonjt commented
@ebolyen is this conda issue identified [here](https://forum.qiime2.org/t/new-conda-installation-scheme/2528)

2018-01-11 16:43 UTC, ebolyen commented
@mortonjt, yup, we haven't gone through to update travis to use the new instructions yet. We'll probably get that sorted out sometime today.

2018-01-12 18:03 UTC, ebolyen commented
@mortonjt, travis.yml has been updated, but you might need to rebase this PR

2018-01-16 18:23 UTC, mortonjt commented
PR rebased @ebolyen thanks!

2018-01-18 22:46 UTC, jairideout commented
@mortonjt, sorry for the trouble, can you please rebase and fix the merge conflicts? This code was updated as part of the Metadata overhaul in #32.

2018-01-19 05:58 UTC, mortonjt commented
Not a problem.  Just rebased.  Let's see if the tests are still ok.

2018-01-19 16:35 UTC, jairideout commented
Let me know if you need help debugging this -- I'm not sure what you're going for in the current PR diff, looks like a partial revert to the pre-Metadata overhaul?

2018-01-19 18:20 UTC, mortonjt commented
Things got a little mixed up during the rebasing :/ 
Investigating ...

2018-01-20 01:58 UTC, mortonjt commented
Looks like the tests are passing.  Not sure why the coverage went down (we added more tests).

2018-01-22 22:05 UTC, jairideout requested changes
Thanks @mortonjt! I had a couple of comments related to the new Metadata API (one of the comments should help you resolve the coverage drop you're seeing).

2018-01-22 22:05 UTC, jairideout commented on q2_gneiss/plot/_plot.py
> +            c = c.astype(np.float64)
Type-casting is no longer necessary with the new Metadata objects -- `NumericMetadataColumn` has the data stored as floating point values.

2018-01-22 22:05 UTC, jairideout commented on q2_gneiss/plot/_plot.py
> +            if threshold is not None:
When I updated the plugin to use the new Metadata API, I moved this check earlier in the method (see [this line](https://github.com/qiime2/q2-gneiss/pull/29/files#diff-9df90a58a11c42324dad341ada319215R40)). Removing the check here will probably fix the drop in coverage.

2018-01-24 19:50 UTC, mortonjt commented on q2_gneiss/plot/_plot.py
> +            c = c.astype(np.float64)
That's awesome!

2018-01-24 19:55 UTC, mortonjt commented
Thanks @jairideout for looking over this!

2018-01-25 18:28 UTC, jairideout approved these changes
Looks great, thanks @mortonjt!

2018-01-25 18:32 UTC, merged

2018-01-25 19:00 UTC, mortonjt commented
Thanks guys!