Update descriptions of _regression.py
qiime2/q2-gneiss pull request #42
Opened 2018-08-21 18:10 UTC by lisa55asil

Brief summary of the Pull Request, including any issues it may fix using the GitHub closing syntax:

https://help.github.com/articles/closing-issues-using-keywords/

Also, include any co-authors or contributors using the GitHub coauthor tag:

https://help.github.com/articles/creating-a-commit-with-multiple-authors/

---

Include any questions for reviewers, screenshots, sample outputs, etc.

2018-08-22 18:47 UTC, mortonjt commented
@lisa55asil from the error messages, it looks like the lines are too long.  Could you break up the lines that you've added?  There is a 79 character limit for each line.

2018-08-23 18:56 UTC, mortonjt commented
I think conda is just being derpy with this one.  @thermokarst could we restart the build?

2018-08-24 17:26 UTC, ebolyen commented
Still a bunch of flake8 errors.

(You can install flake8 to test locally via `conda install flake8` then just run `flake8` in your source directory :) )

2018-08-29 16:21 UTC, ebolyen commented
@lisa55asil or @mortonjt, would you be able to fix the flake8 errors so we can merge? (Worst case I can do that, but there's a bunch of other PRs to get to today). Thanks!

2018-08-29 18:00 UTC, ebolyen requested changes

2018-08-29 18:00 UTC, ebolyen commented on q2_gneiss/regression/_regression.py
> +                   'will be used in the regression model,
Missing closing `'`

2018-08-29 18:00 UTC, ebolyen commented on q2_gneiss/regression/_regression.py
> +                  'simplicial regression with mixed effects'
missing trailing space

2018-08-29 18:00 UTC, ebolyen commented on q2_gneiss/regression/_regression.py
>      description="Build and run linear mixed effects model on balances."
Needs a trailing space

2018-08-29 18:02 UTC, ebolyen commented on q2_gneiss/regression/_regression.py
> +        'formula': 'Statistical formula specifying the statistical model.'
Oh here as well

2018-08-29 18:29 UTC, mortonjt commented
Can't seem to push directly -- can only edit on the main github main page ..

Hopefully this should just do it ...

2018-08-29 19:15 UTC, ebolyen commented
The github editor has betrayed you.

To push to a remote you don't own there's usually extra syntax needed:

```
git push <remote> <local-branch>:<remote-branch>
```

Unless you have the exact same branch name locally, GitHub will throw it away since you won't have permissions for `<local-branch>` only `<remote-branch>`

2018-08-29 20:10 UTC, closed without merging

2018-08-29 20:11 UTC, mortonjt commented
crap, that closed it XD

2018-08-29 20:25 UTC, ebolyen commented
Wow everything has disappeared!

2018-08-29 20:28 UTC, mortonjt commented
I opened a new PR - looks like that update rewrote everything :L

On Wed, Aug 29, 2018, 1:25 PM Evan Bolyen <notifications@github.com> wrote:

> Wow everything has disappeared!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/qiime2/q2-gneiss/pull/42#issuecomment-417093659>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AD_a3XbFpupC7O-zVo67lfydkJYYeQ1hks5uVviogaJpZM4WGUjy>
> .
>