(WIP) added ilr-phylogenetic
qiime2/q2-gneiss pull request #43
Opened 2018-08-22 22:05 UTC by qiyunzhu

Addressed issue #41 @mortonjt 

Brief summary of the Pull Request, including any issues it may fix using the GitHub closing syntax:

https://help.github.com/articles/closing-issues-using-keywords/

Also, include any co-authors or contributors using the GitHub coauthor tag:

https://help.github.com/articles/creating-a-commit-with-multiple-authors/

---

Include any questions for reviewers, screenshots, sample outputs, etc.

2018-08-23 18:55 UTC, mortonjt commented
I approve!

2018-08-23 18:55 UTC, mortonjt approved these changes

2018-08-24 17:21 UTC, ebolyen requested changes
Looks good, just a couple of minor things in the registration.

@mortonjt or @qiyunzhu, would either of you be able to create a corresponding docs PR for the gniess tutorial? Thanks!

2018-08-24 17:21 UTC, ebolyen commented on q2_gneiss/composition/_composition.py
> +                                      'ilr transform.')},
Can we add a description for the tree? I assume this tree has the new internal node labels right?

2018-08-24 17:21 UTC, ebolyen commented on q2_gneiss/composition/_method.py
> +    return ilr_transform(table, t), t
:+1:

2018-08-24 17:21 UTC, ebolyen commented on q2_gneiss/composition/tests/test_method.py
> +            '((c:0.025,d:0.025,e:0.025):0.2,(b:0.025,a:0.025):0.2);'])
:+1: for testing the bifurcation

2018-08-24 17:21 UTC, ebolyen commented on q2_gneiss/composition/_composition.py
> +    description="Calculate balances given a hierarchy."
"Calculate balances given a rooted phylogeny."

2018-08-24 17:21 UTC, ebolyen commented on q2_gneiss/composition/_composition.py
> +    name='Isometric Log-ratio Transform',
Let's give these slightly different names

2018-08-24 18:44 UTC, qiyunzhu commented
Hi @ebolyen Thanks for your feedbacks! Regarding docs, I think Lisa is working on them in a separate PR. @mortonjt is that right?

2018-08-24 18:45 UTC, mortonjt commented
Yup. That's correct

On Fri, Aug 24, 2018, 11:44 AM Qiyun Zhu <notifications@github.com> wrote:

> Hi @ebolyen <https://github.com/ebolyen> Thanks for your feedbacks!
> Regarding docs, I think Lisa is working on them in a separate PR.
> @mortonjt <https://github.com/mortonjt> is that right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/qiime2/q2-gneiss/pull/43#issuecomment-415848076>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AD_a3eJNGf_4ao4fDgyHos1al157A1rbks5uUEmOgaJpZM4WIftN>
> .
>

2018-08-24 23:00 UTC, mortonjt commented on q2_gneiss/composition/_composition.py
> +             ('tree', Phylogeny[Rooted])],
Can we convert this tree to a hierarchy so that the regression summaries don't crash downstream?

2018-08-26 22:53 UTC, qiyunzhu commented
travis build was stalled, any idea? @mortonjt

2018-08-26 23:35 UTC, qiyunzhu commented
Done! @mortonjt @ebolyen

2018-08-27 18:00 UTC, ebolyen approved these changes
LGTM! Merge-pending Docs PR so that our CI system can still test other things.

2018-08-29 21:23 UTC, lisa55asil commented on q2_gneiss/composition/_composition.py
> +    name='Isometric Log-ratio Transform',
Can you specify this to be specific for hierarchies?

For instance
`Isometric Log-ratio Transform applied to a hierarchical clustering`

2018-08-29 21:23 UTC, lisa55asil commented on q2_gneiss/composition/_composition.py
>      name='Isometric Log-ratio Transform',
Same thing here, can you change this to something like

`Isometric Log-ratio Transform applied to a phylogenetic tree`

2018-08-29 21:44 UTC, merged

2018-08-29 21:45 UTC, ebolyen commented
Thanks @qiyunzhu! And everyone else who reviewed!

2018-08-29 22:38 UTC, qiyunzhu commented
@ebolyen Thank you very much!